### ISSUE TITLE
快速设置currentPage，page的位置有问题。

### ISSUE THREAD

**Issue by li-qingnan** [wayone/WOPageControl-OC#1]
快速设置currentPage，page的位置有问题。

会被 self.inAnimating 的判断给拦截住，造成page的位置不对。
请作者修复一下。

**Comment by wayone** [comment]
如果快速修改，在动画效果上，一个动画还没结束，又开始下一个动画，可能会错乱，暂时没有想到合适的动画效果。现在这个动画效果是比较“干净利索”的。你可以修改一下你的调用代码，避免快速调用。在你的图片滚动停止后再调用。这样，出现快速修改的可能性就很小了，即使出现了，也很少有用户能觉察到。再等下一次修改时，就修正了。
